image: "kolxd/alpine-cloud-utilities"
stages: 
  - dev
  - prod

before_script:
  - mkdir -p ~/.ssh
  - echo "$ssh_private_key" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ansible --version
  - ssh-add ~/.ssh/id_rsa
  - python -m pip install ansible-lint
  - ansible-lint roles/httpserver/tasks/main.yml
  - ansible-lint roles/dbserver/tasks/main.yml

development:
  stage: dev
  script:
    - ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i hosts dev-site.yml
  only:
    - merge_requests

production:
  stage: prod
  script:
    - ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i hosts prod-site.yml
  only:
    - master